DROP TABLE IF EXISTS Ligue;
DROP TABLE IF EXISTS Employe;

CREATE TABLE Ligue (
    ID_LIGUE INT,
    NOM_L VARCHAR(255),
    PRIMARY KEY(ID_LIGUE)
) ENGINE = InnoDB;

CREATE TABLE Employe (
    ID_EMP INT,
    NOM_EMP VARCHAR(255),
    PRENOM_EMP VARCHAR(255),
    MDP_EMP VARCHAR(255),
    DATE_ARRIVE DATE,
    DATE_DEPART DATE,  
    ADMIN BOOLEAN,
    MAIL_EMP VARCHAR(255),
    ID_LIGUE INT,
    PRIMARY KEY(ID_EMP),
    FOREIGN KEY(ID_LIGUE) REFERENCES Ligue(ID_LIGUE)
) ENGINE = InnoDB;
